import QRCode from 'qrcode';
import { setToolStep, toolPageTemplate } from '../../../components/toolLayout.js';
import { downloadBlob } from '../../../utils/download.js';

function escapeQr(value) { return value.replace(/([\\;,:"])/g, '\\$1'); }

export function qrCodeTemplate() {
  return toolPageTemplate({ category: '日常工具', categoryPath: '/category/daily', eyebrow: 'DAILY TOOL', title: 'QR Code 產生器', iconName: 'qr', description: '建立網址、Wi-Fi、文字或聯絡人 QR Code，可自訂顏色與尺寸。', steps: ['選擇內容類型', '輸入與預覽', '下載 PNG'], content: `<section class="workspace qr-workspace"><div class="tool-controls qr-controls"><div class="mode-tabs" role="tablist"><button class="active" type="button" data-mode="url">網址</button><button type="button" data-mode="wifi">Wi-Fi</button><button type="button" data-mode="text">文字</button><button type="button" data-mode="contact">聯絡人</button></div><div class="qr-layout"><div class="qr-fields"><div data-fields="url"><label><span class="field-label">網址</span><input id="qr-url" class="setting-input" type="url" placeholder="https://example.com" /></label></div><div data-fields="wifi" hidden><label><span class="field-label">Wi-Fi 名稱</span><input id="wifi-name" class="setting-input" type="text" /></label><label><span class="field-label">Wi-Fi 密碼</span><input id="wifi-password" class="setting-input" type="text" /></label><label class="check-label"><input id="wifi-hidden" type="checkbox" />隱藏網路</label></div><div data-fields="text" hidden><label><span class="field-label">文字內容</span><textarea id="qr-text" class="setting-input qr-textarea" maxlength="1200"></textarea></label></div><div data-fields="contact" hidden><div class="settings-grid"><label><span class="field-label">姓名</span><input id="contact-name" class="setting-input" type="text" /></label><label><span class="field-label">電話</span><input id="contact-phone" class="setting-input" type="tel" /></label></div><label><span class="field-label">Email</span><input id="contact-email" class="setting-input" type="email" /></label></div><div class="settings-grid qr-options"><label><span class="field-label">前景顏色</span><input id="qr-color" class="setting-input color-input" type="color" value="#0b1f4b" /></label><label><span class="field-label">背景顏色</span><input id="qr-background" class="setting-input color-input" type="color" value="#ffffff" /></label></div><label class="range-label" for="qr-size"><span>圖片尺寸</span><strong id="qr-size-value">640 px</strong></label><input id="qr-size" class="range-input" type="range" min="256" max="1024" step="64" value="640" /></div><div class="qr-preview"><img id="qr-image" alt="QR Code 預覽" hidden /><p id="qr-placeholder">輸入內容後<br />這裡會即時顯示 QR Code</p></div></div><div id="status" class="status" role="status"></div><button id="action-button" class="primary-button" type="button" disabled>下載 QR Code PNG</button></div></section>` });
}

export function bindQrCode() {
  let mode = 'url'; let dataUrl = ''; let timer; const image = document.querySelector('#qr-image'); const placeholder = document.querySelector('#qr-placeholder'); const status = document.querySelector('#status'); const action = document.querySelector('#action-button'); const size = document.querySelector('#qr-size');
  function content() { if (mode === 'url') return document.querySelector('#qr-url').value.trim(); if (mode === 'text') return document.querySelector('#qr-text').value.trim(); if (mode === 'wifi') { const name = document.querySelector('#wifi-name').value.trim(); if (!name) return ''; return `WIFI:T:WPA;S:${escapeQr(name)};P:${escapeQr(document.querySelector('#wifi-password').value)};H:${document.querySelector('#wifi-hidden').checked};;`; } const name = document.querySelector('#contact-name').value.trim(); if (!name) return ''; return `BEGIN:VCARD\nVERSION:3.0\nFN:${name}\nTEL:${document.querySelector('#contact-phone').value.trim()}\nEMAIL:${document.querySelector('#contact-email').value.trim()}\nEND:VCARD`; }
  async function render() { const value = content(); if (!value) { dataUrl = ''; image.hidden = true; placeholder.hidden = false; action.disabled = true; status.textContent = ''; setToolStep(1); return; } try { dataUrl = await QRCode.toDataURL(value, { width: Number(size.value), margin: 2, errorCorrectionLevel: 'M', color: { dark: document.querySelector('#qr-color').value, light: document.querySelector('#qr-background').value } }); image.src = dataUrl; image.hidden = false; placeholder.hidden = true; action.disabled = false; status.className = 'status success'; status.textContent = '預覽已更新，建議下載後用手機測試掃描。'; setToolStep(2); } catch (error) { status.className = 'status error'; status.textContent = '內容過長，請縮短後再試。'; } }
  function schedule() { clearTimeout(timer); timer = setTimeout(render, 160); }
  document.querySelector('.mode-tabs').addEventListener('click', (event) => { if (!event.target.dataset.mode) return; mode = event.target.dataset.mode; document.querySelectorAll('.mode-tabs button').forEach((button) => button.classList.toggle('active', button === event.target)); document.querySelectorAll('[data-fields]').forEach((group) => { group.hidden = group.dataset.fields !== mode; }); schedule(); });
  document.querySelector('.qr-controls').addEventListener('input', schedule); size.addEventListener('input', () => { document.querySelector('#qr-size-value').textContent = `${size.value} px`; });
  action.addEventListener('click', async () => { const blob = await (await fetch(dataUrl)).blob(); downloadBlob(blob, 'qrcode.png'); status.textContent = 'QR Code PNG 已下載。'; setToolStep(3); });
}
