import JSZip from 'jszip';
import { bindFilePicker, filePickerTemplate, toolPageTemplate } from '../../../components/toolLayout.js';
import { downloadBlob, formatBytes } from '../../../utils/download.js';

export function zipToolTemplate() {
  return toolPageTemplate({ category: '日常工具', categoryPath: '/category/daily', eyebrow: 'FILE TOOL', title: 'ZIP 打包／解壓', iconName: 'zip', description: '將多個檔案打包成 ZIP，或查看並解開現有 ZIP 檔案。', content: `<section class="workspace tool-workspace"><div class="mode-tabs zip-tabs" role="tablist"><button class="active" type="button" data-mode="create">建立 ZIP</button><button type="button" data-mode="extract">解開 ZIP</button></div>${filePickerTemplate({ accept: '*/*', multiple: true, title: '拖放要打包的檔案', hint: '可一次加入多個檔案，原始檔不會被修改' })}<div id="tool-controls" class="tool-controls" hidden><div class="panel-heading"><div><p id="zip-heading" class="section-label">待打包檔案</p><p id="selected-meta" class="file-summary"></p></div><button id="replace-file" class="text-button" type="button">重新選擇</button></div><div id="zip-file-list" class="zip-file-list"></div><div id="create-settings"><label class="field-label" for="zip-name">ZIP 檔名</label><input id="zip-name" class="setting-input" type="text" value="Toolbox-檔案" /></div><div id="status" class="status" role="status" aria-live="polite"></div><button id="action-button" class="primary-button" type="button">建立並下載 ZIP</button></div></section>` });
}

export function bindZipTool() {
  const dropZone = document.querySelector('#drop-zone'); const controls = document.querySelector('#tool-controls'); const list = document.querySelector('#zip-file-list'); const input = document.querySelector('#file-input'); const status = document.querySelector('#status'); const action = document.querySelector('#action-button'); let mode = 'create'; let files = []; let zipEntries = [];
  function renderCreate() { list.innerHTML = files.map((file, index) => `<article class="zip-file-row"><span class="file-type-badge">${file.name.split('.').pop().slice(0, 4).toUpperCase()}</span><div><strong>${file.name}</strong><small>${formatBytes(file.size)}</small></div><button type="button" data-remove="${index}" aria-label="移除 ${file.name}">×</button></article>`).join(''); document.querySelector('#selected-meta').textContent = `${files.length} 個檔案 · ${formatBytes(files.reduce((sum, file) => sum + file.size, 0))}`; }
  function renderExtract() { list.innerHTML = zipEntries.map((entry, index) => `<label class="zip-file-row"><input type="checkbox" data-entry="${index}" ${entry.dir ? 'disabled' : 'checked'} /><span class="file-type-badge">${entry.dir ? 'DIR' : entry.name.split('.').pop().slice(0, 4).toUpperCase()}</span><div><strong>${entry.name}</strong><small>${entry.dir ? '資料夾' : '準備解壓縮'}</small></div></label>`).join(''); document.querySelector('#selected-meta').textContent = `${zipEntries.filter((entry) => !entry.dir).length} 個檔案`; }
  async function selectFiles(selected) { status.textContent = ''; if (mode === 'create') { files = selected; if (!files.length) return; renderCreate(); } else { const file = selected.find((item) => item.name.toLowerCase().endsWith('.zip')); if (!file) { dropZone.querySelector('.drop-hint').textContent = '請選擇 ZIP 檔案。'; return; } try { const zip = await JSZip.loadAsync(file); zipEntries = Object.values(zip.files); renderExtract(); } catch { dropZone.querySelector('.drop-hint').textContent = '無法讀取這個 ZIP，可能已加密或檔案損壞。'; return; } } dropZone.hidden = true; controls.hidden = false; }
  bindFilePicker(selectFiles);
  document.querySelector('.zip-tabs').addEventListener('click', (event) => { if (!event.target.dataset.mode || event.target.dataset.mode === mode) return; mode = event.target.dataset.mode; document.querySelectorAll('.zip-tabs button').forEach((button) => button.classList.toggle('active', button === event.target)); files = []; zipEntries = []; controls.hidden = true; dropZone.hidden = false; input.accept = mode === 'extract' ? '.zip,application/zip' : '*/*'; input.multiple = mode === 'create'; dropZone.querySelector('.drop-title').textContent = mode === 'create' ? '拖放要打包的檔案' : '拖放一個 ZIP 到這裡'; dropZone.querySelector('.drop-hint').textContent = mode === 'create' ? '可一次加入多個檔案，原始檔不會被修改' : '選取後可查看內容並選擇要解開的檔案'; document.querySelector('#zip-heading').textContent = mode === 'create' ? '待打包檔案' : 'ZIP 內容'; document.querySelector('#create-settings').hidden = mode === 'extract'; action.textContent = mode === 'create' ? '建立並下載 ZIP' : '解壓縮選取檔案'; });
  document.querySelector('#replace-file').addEventListener('click', () => input.click());
  list.addEventListener('click', (event) => { if (event.target.dataset.remove == null) return; files.splice(Number(event.target.dataset.remove), 1); renderCreate(); if (!files.length) { controls.hidden = true; dropZone.hidden = false; } });
  action.addEventListener('click', async () => { action.disabled = true; status.className = 'status working'; try { if (mode === 'create') { const zip = new JSZip(); files.forEach((file) => zip.file(file.name, file)); const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' }, (metadata) => { status.textContent = `正在打包… ${Math.round(metadata.percent)}%`; }); const name = document.querySelector('#zip-name').value.trim().replace(/[\\/:*?"<>|]/g, '-') || 'Toolbox-檔案'; downloadBlob(blob, `${name}.zip`); status.className = 'status success'; status.textContent = `完成！已打包 ${files.length} 個檔案。`; } else { const selected = [...list.querySelectorAll('[data-entry]:checked')].map((checkbox) => zipEntries[Number(checkbox.dataset.entry)]); if (!selected.length) throw new Error('請至少選擇一個檔案。'); if ('showDirectoryPicker' in window) { const directory = await window.showDirectoryPicker({ mode: 'readwrite' }); for (const entry of selected) { status.textContent = `正在寫入 ${entry.name}…`; const handle = await directory.getFileHandle(entry.name.split('/').filter(Boolean).pop(), { create: true }); const writable = await handle.createWritable(); await writable.write(await entry.async('blob')); await writable.close(); } } else { for (const entry of selected) downloadBlob(await entry.async('blob'), entry.name.split('/').filter(Boolean).pop()); } status.className = 'status success'; status.textContent = `完成！已解開 ${selected.length} 個檔案。`; } } catch (error) { if (error.name !== 'AbortError') { status.className = 'status error'; status.textContent = error.message || '處理失敗，請更換檔案後再試。'; } } finally { action.disabled = false; } });
}
