import { setToolStep, toolPageTemplate } from '../../../components/toolLayout.js';
import { downloadBlob } from '../../../utils/download.js';
import { csvToJson, jsonToCsv } from '../../../utils/text.js';

export function csvJsonTemplate() {
  return toolPageTemplate({ category: '日常工具', categoryPath: '/category/daily', eyebrow: 'DATA CONVERTER', title: 'CSV／JSON 轉換', iconName: 'csvJson', description: 'CSV 與 JSON 雙向轉換，支援引號、逗號與換行內容。', steps: ['選擇轉換方向', '貼上資料', '下載結果'], content: `<section class="workspace text-workspace"><div class="tool-controls"><div class="mode-tabs" role="tablist"><button class="active" type="button" data-mode="csvToJson">CSV → JSON</button><button type="button" data-mode="jsonToCsv">JSON → CSV</button></div><div class="cleanup-columns converter-columns"><label><span id="source-label" class="field-label">CSV 內容</span><textarea id="source-data" class="large-textarea code-textarea" spellcheck="false" placeholder="name,age&#10;Amy,28"></textarea></label><label><span id="result-label" class="field-label">JSON 結果</span><textarea id="result-data" class="large-textarea code-textarea" readonly placeholder="轉換結果"></textarea></label></div><div id="status" class="status" role="status" aria-live="polite"></div><div class="action-pair"><button id="convert-button" class="primary-button" type="button">轉換成 JSON</button><button id="copy-button" class="secondary-action" type="button">複製結果</button><button id="download-button" class="secondary-action" type="button">下載結果</button></div></div></section>` });
}

export function bindCsvJson() {
  const source = document.querySelector('#source-data'); const result = document.querySelector('#result-data'); const status = document.querySelector('#status'); let mode = 'csvToJson';
  function updateLabels() { const csvFirst = mode === 'csvToJson'; document.querySelector('#source-label').textContent = csvFirst ? 'CSV 內容' : 'JSON 內容'; document.querySelector('#result-label').textContent = csvFirst ? 'JSON 結果' : 'CSV 結果'; document.querySelector('#convert-button').textContent = csvFirst ? '轉換成 JSON' : '轉換成 CSV'; source.placeholder = csvFirst ? 'name,age\nAmy,28' : '[{"name":"Amy","age":28}]'; source.value = ''; result.value = ''; status.textContent = ''; setToolStep(1); }
  document.querySelector('.mode-tabs').addEventListener('click', (event) => { if (!event.target.dataset.mode) return; mode = event.target.dataset.mode; document.querySelectorAll('.mode-tabs button').forEach((button) => button.classList.toggle('active', button === event.target)); updateLabels(); });
  source.addEventListener('input', () => setToolStep(source.value.trim() ? 2 : 1));
  function convert() { try { if (mode === 'csvToJson') { const value = csvToJson(source.value); result.value = JSON.stringify(value, null, 2); status.textContent = `完成！已轉換 ${value.length} 筆資料。`; } else { const value = JSON.parse(source.value); result.value = jsonToCsv(value); status.textContent = `完成！已轉換 ${value.length} 筆資料。`; } status.className = 'status success'; setToolStep(3); return true; } catch (error) { status.className = 'status error'; status.textContent = `無法轉換：${error.message}`; return false; } }
  document.querySelector('#convert-button').addEventListener('click', convert);
  document.querySelector('#copy-button').addEventListener('click', async () => { if (!result.value && !convert()) return; await navigator.clipboard.writeText(result.value); status.textContent = '轉換結果已複製。'; });
  document.querySelector('#download-button').addEventListener('click', () => { if (!result.value && !convert()) return; const json = mode === 'csvToJson'; downloadBlob(new Blob([result.value], { type: json ? 'application/json;charset=utf-8' : 'text/csv;charset=utf-8' }), json ? 'converted.json' : 'converted.csv'); status.textContent = '轉換結果已下載。'; });
}
